version: '3.9'

services:
  mento-nextjsAGI:
    image: ghcr.io/enricoros/big-agi:main
    ports:
      - "3003:3000" #As 3000 us mostly used
    env_file:
      - .env
    command: [ "next", "start", "-p", "3000" ]
